### ISSUE TITLE
Migrate wiki from espes/xqemu

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu_old#4]
The wiki contained some good info. Either that info should be captured on another wiki (perhaps a page on xboxdevwiki.net) or migrated to this repo.

**Comment by JayFoxRox** [comment]
Related to #92 .

I think we should move the wiki repo directly. The information is specific to XQEMU so it should not just be part of xboxdevwiki (which should mostly contain official Xbox information / research).

**Comment by mborgerson** [comment]
We do have a [page about XQEMU](http://xboxdevwiki.net/XQEMU) on XBDW that's getting pretty large, I think adding info there would be okay so we don't have the info in two different spots. I also think the MediaWiki is more capable compared to the GitHub wiki. I'm fine with either way, but I'd prefer info to be in one spot if possible.

**Comment by JayFoxRox** [comment]
The wiki page contains the most basic info about the project and the compatibility list.
We don't have any other infrastructure to store such information currently.

I've also shortened most non-official / homebrew articles on xboxdevwiki in the past, and will continue to do so.
There is little point in mixing unofficial and official info / research.
Most unofficial stuff can be moved to the footnotes / linked as related material.

The XQEMU documentation which is critical in setting up XQEMU should stay close to the codebase.
The whole idea of the xqemu/xqemu repo is centralization. Moving away important information would not be beneficial.
We should, however, move the TODOs to the GitHub issues ( #82 ) and possibly also move information which is unlikely to change, into the readme.

**Comment by mborgerson** [comment]
For some reason it looks like I can make edits from the web, but not push to the wiki from my Git client. Somebody else will have to do it.

**Comment by espes** [comment]
@mborgerson ive made you an owner of the org aswell, so should be able to fix any permission issues

**Comment by mborgerson** [comment]
Done. Migrated to https://github.com/xqemu/xqemu.
